#Dockerfile
FROM python:3

#Copiar los scripts al contenedor
COPY main.py /app/

#Establecer el directorio de trabajo
WORKDIR /app

#Ejecutar el script cuando el contenedor se inicie
CMD [ "python", "main.py" ]