version: '3'
services:
  master:
    image: mysql:latest
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=test
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"

  slave:
    image: mysql:latest
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=test
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
    depends_on:
      - master
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOSTS: master,slave
    ports:
      - "8080:80"
    depends_on:
      - master
      - slave
